src/Entity/Basket.php
<?php

namespace App\Entity;

use App\Repository\BasketRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BasketRepository::class)]
class Basket
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?User $Users = null;

    #[ORM\OneToMany(mappedBy: 'basket', targetEntity: Product::class)]
    private Collection $Product;

    #[ORM\Column]
    private ?int $Quantity = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: '0')]
    private ?string $Total_amount = null;

    public function __construct()
    {
        $this->Product = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsers(): ?User
    {
        return $this->Users;
    }

    public function setUsers(?User $Users): self
    {
        $this->Users = $Users;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProduct(): Collection
    {
        return $this->Product;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->Product->contains($product)) {
            $this->Product->add($product);
            $product->setBasket($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->Product->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getBasket() === $this) {
                $product->setBasket(null);
            }
        }

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getTotalAmount(): ?string
    {
        return $this->Total_amount;
    }

    public function setTotalAmount(string $Total_amount): self
    {
        $this->Total_amount = $Total_amount;

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Entity\Order;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProductRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[Vich\Uploadable]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $Name = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column]
    private ?float $Price = null;

    #[ORM\Column(length: 5)]
    private ?string $Size = null;

    #[ORM\Column(length: 100)]
    private ?string $Color = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Brand $Brand = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $Category = null;

    #[ORM\ManyToMany(targetEntity: Order::class, mappedBy: 'Product')]
    private Collection $orders;

    #[ORM\ManyToOne(inversedBy: 'Product')]
    private ?Basket $basket = null;


    
    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $Created_at = null;
    
    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $Updated_at = null;
    
    #[ORM\Column(length: 255, type: 'string')]
    private ?string $attachment = null;
    
    
    #[Vich\UploadableField(mapping: 'products', fileNameProperty: 'attachment')]
    private ?File $attachmentFile = null;
    
    
    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }
    
    public function getName(): ?string
    {
        return $this->Name;
    }
    
    public function setName(string $Name): self
    {
        $this->Name = $Name;
        
        return $this;
    }
    
    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getSize(): ?string
    {
        return $this->Size;
    }

    public function setSize(string $Size): self
    {
        $this->Size = $Size;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->Color;
    }

    public function setColor(string $Color): self
    {
        $this->Color = $Color;

        return $this;
    }

    public function getBrand(): ?Brand
    {
        return $this->Brand;
    }

    public function setBrand(?Brand $Brand): self
    {
        $this->Brand = $Brand;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->addProduct($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            $order->removeProduct($this);
        }

        return $this;
    }

    public function getBasket(): ?Basket
    {
        return $this->basket;
    }

    public function setBasket(?Basket $basket): self
    {
        $this->basket = $basket;

        return $this;
    }


    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->Created_at;
    }

    public function setCreatedAt(?\DateTimeImmutable $Created_at): self
    {
        $this->Created_at = $Created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->Updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $Updated_at): self
    {
        $this->Updated_at = $Updated_at;

        return $this;
    }

    public function getAttachment(): ?string
    {
        return $this->attachment;
    }

    public function setAttachment(?string $attachment): self
    {
        $this->attachment = $attachment;

        return $this;
    }

    public function getAttachmentFile(): ?File
    {
        return $this->attachmentFile;
    }
    public function setAttachmentFile(?File $attachmentFile = null): void
    {
        $this->attachmentFile = $attachmentFile;
        if (null !== $attachmentFile) {
            $this->Updated_at = new \DateTimeImmutable();
        }
    }
}

src/Controller/BasketController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Service\BasketService;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BasketController extends AbstractController
{

    // permet d'afficher le panier

    #[Route('/mon-panier', name: 'basket_index')]
    public function index(BasketService $basketService): Response
    {   
        
        return $this->render('basket/index.html.twig',[
                
                'basket' => $basketService->getTotal()
        ]);
    }

    // permet d'ajouter un produit au panier

    #[Route('/mon-panier/add/{id<\d+>}', name: 'basket_add')]
    public function addToBasket(BasketService $basketService, int $id): Response
    {
        $basketService->addToBasket($id);

        return $this->redirectToRoute('basket_index');
    }


    // permet de supprimer un produit du panier

    #[Route('/mon-panier/remove/{id<\d+>}', name: 'basket_remove')]
    public function removeBasket(BasketService $basketService, int $id): Response
    {
        $basketService->removeBasket($id);

        return $this->redirectToRoute('basket_index');
    }

    // permet de diminuer la quantité d'un produit du panier
    #[Route('/mon-panier/decrease/{id<\d+>}', name: 'basket_decrease')]
    public function decrease(BasketService $basketService, int $id): RedirectResponse
    {
        $basketService->decrease($id);

        return $this->redirectToRoute('basket_index');
    }


    // permet de supprimer tous les produits du panier

    #[Route('/mon-panier/removeAll', name: 'basket_removeAll')]
    public function removeBasketAll(BasketService $basketService): Response
    {
        $basketService->removeBasketAll();

        return $this->redirectToRoute('product_index');
    }
}
   

templates/basket/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier{% endblock %}

{% block body %}

<main class="page-wrapper">

    {% if basket|length > 0 %}


                
                
                <style>
                    @layer utilities {
                        input[type="number"]::-webkit-inner-spin-button,
                        input[type="number"]::-webkit-outer-spin-button {
                            -webkit-appearance: none;
                            margin: 0;
                        }
                    }
                </style>
                
                <body>
                    
                    <h1 class="mb-10 text-center text-2xl font-bold">Mon panier</h1>
                    <div class="mx-auto max-w-5xl justify-center px-6 md:flex md:space-x-6 xl:px-0">
                      <div class="rounded-lg md:w-2/3">
                        <a href="{{ path('basket_removeAll') }}" class="btn btn-outline-dark btn-sm">Vider le panier</a>
                        {% set total =null %}
                        {% for item in basket %}
                        {% set total = total + item.product.price * item.quantity %}
                        <div class="justify-between mb-6 rounded-lg bg-white p-6 shadow-md sm:flex sm:justify-start">
                          <img src="{{ vich_uploader_asset(item.product, 'attachmentFile')}}" alt="product-image" class="w-full rounded-lg sm:w-40" />
                          <div class="sm:ml-4 sm:flex sm:w-full sm:justify-between">
                            <div class="mt-5 sm:mt-0">
                              <h2 class="text-lg font-bold text-gray-900">{{ item.product.name }}</h2>
                              <p class="mt-1 text-xs text-gray-700">{{ item.product.size }}</p>
                            </div>
                            <div class="mt-4 flex justify-between sm:space-y-6 sm:mt-0 sm:block sm:space-x-6">
                              
                              <div class="flex items-center border-gray-100">
                                
                                <a href="{{ path('basket_decrease', {id:item.product.id})}}"><span class="cursor-pointer rounded-l bg-gray-100 py-1 px-3.5 duration-100 hover:bg-blue-500 hover:text-blue-50" data-decrement> - </span>
                                  <input class="h-8 w-8 border bg-white text-center text-xs outline-none" type="number" value="{{ item.quantity }}" min="1" />
                                  
                                  <a href="{{ path('basket_add', {id:item.product.id})}}"><span class="cursor-pointer rounded-r bg-gray-100 py-1 px-3 duration-100 hover:bg-blue-500 hover:text-blue-50" data-increment> + </span>
                                  </div>
                                  
                                  <div class="flex items-center space-x-4">
                                    <p class="text-lg font-bold text-gray-900">{{ (total/100)|number_format(2, ',', '.') }} €</p>
                                    
                                    
                                    <button class="btn btn-circle">
                                      <a href="{{path ('basket_decrease', {id: item.product.id})}}">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
                                      </button>
                                      
                                    </div>
                                  </div>
                                </div>
                              </div>
                              
                              <form action="{{ path ('order_index')}}">
                {% endfor %}
                Nombre de produit :
                {{ basket|length }}
                <br>
                
                <ul class="list-unstyled py-3 mb-0">
                    <li class="d-flex justify-content-between align-items-center border-bottom py-3">
                        <strong class="text-muted">Total</strong>
                        <h5 class="font-weight-bold">{{ (total/100)|number_format(2, ',', '.') }} €</h5>
                    </li>
                </ul>
                <div class="d-flex justify-content-between align-items-center pt-3 mb-4">
                    <a class="btn btn-outline-dark btn-sm" href="{{ path('product_index') }}">Continuer mes achats</a>
                    <button class="btn btn-primary btn-sm" type="submit">Valider mon panier</button>
                
        </form>
                
    {% else %}
<div class="container d-flex flex-column justify-content-center min-vh-100 py-5">
    <div class="text-center pt-4 mt-lg-2">
        <h1 class="display-5">Votre panier est vide</h1>
        <p class="fs-lg pb-2 pb-md-0 mb-4 mb-md-5">Commencez votre shopping dès maintenant !</p>
        <a class="btn btn-primary btn-lg" href="{{ path('product_index') }}">Voir les articles</a>
    </div>
    {% endif %}

</main>


{% endblock %}